GET http://localhost:3000/locations

###

GET http://localhost:3000/locations/5e371b45568cf24260d66ada

###

POST http://localhost:3000/locations
Content-Type: application/json

{
    "title": "stuff",
    "latitude": 44,
    "longitude": 66
}

###

DELETE http://localhost:3000/locations/5e38a83614ed010dbcd50c12

###

PATCH http://localhost:3000/locations/5e37313e5e309c07ad57bc60
Content-Type: application/json

{
    "title": "Tommy",
    "longitude": 100
}